parameters:
#    gest_stages_stage.example.class: gestStages\StageBundle\Example

services:
#    gest_stages_stage.example:
#        class: %gest_stages_stage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
